global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["dev_backend:8000"]
        labels:
          env: "dev"
      # - targets: ["prod_backend:8000"]
      #   labels:
      #     env: "prod"

  - job_name: "batch"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["dev_batch:8000"]
        labels:
          env: "dev"
      # - targets: ["prod_batch:8000"]
      #   labels:
      #     env: "prod"
